### 
get https://backend-library-2j6c.onrender.com/books


###
get http://localhost:5000/books/6626ab22edbe06344f7e9aae


###
post http://localhost:5000/books
Content-Type: application/json

 {
    "title": "Cien años de soledad",
    "description": "Novela de García Márquez. La saga de los Buendía en Macondo, con elementos de realismo mágico.",
    "pages": 100,
    "image_url": "https://images.cdn3.buscalibre.com/fit-in/360x360/61/8d/618d227e8967274cd9589a549adff52d.jpg",
    "publication_date": "1968",
    "extract": "Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielos."
  }


###
PATCH  http://localhost:5000/books/6626ab22edbe06344f7e9aae
Content-Type: application/json

{
  "title": "Don quijote de la mancha"
}

###
DELETE http://localhost:5000/books/6626b4c4d65553a683c3d313